mv snip_cg_05day-anom_e_afr.html snip_cg_05day_anom_e_afr.html
mv snip_cg_05day-zscore_e_afr.html snip_cg_05day_zscore_e_afr.html
mv snip_cg_10day-anom_e_afr.html snip_cg_10day_anom_e_afr.html
mv snip_cg_10day-zscore_e_afr.html snip_cg_10day_zscore_e_afr.html
mv snip_cg_15day-anom_e_afr.html snip_cg_15day_anom_e_afr.html
mv snip_cg_15day-zscore_e_afr.html snip_cg_15day_zscore_e_afr.html
