name: Deploy to Dokku

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DOKKU_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Push to Dokku
      run: |
        ssh-keyscan -p [DOKKU_SSH_PORT] [DOKKU_HOST] >> ~/.ssh/known_hosts
        git remote add dokku [DOKKU_USER]@[DOKKU_HOST]:[APP_NAME]
        git push dokku main
      env:
        DOKKU_SSH_PORT: 22  # Replace with your Dokku SSH port if not 22
        DOKKU_HOST: grit-web02.grit.ucsb.edu         # Replace with your Dokku server's host
        DOKKU_USER: dokku                      # Usually 'dokku'
        APP_NAME: chc-snippets              # Replace with your Dokku app name
