name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/<username>/my-image-name:$(date +%s)

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the Docker image
      run: docker push ghcr.io/<username>/my-image-name:$(date +%s)
