---
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@grit-web02.grit.ucsb.edu:22/chc-snippets'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
