name: Deploy to Dokku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 grit-web02.grit.ucsb.edu >> ~/.ssh/known_hosts

    - name: Deploy to Dokku
      run: |
        git remote remove dokku || true
        git remote add dokku ssh://dokku@grit-web02.grit.ucsb.edu:chc-snippets
        git push dokku main
