name: Deploy to Dokku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: grit-web01
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure the entire git history is fetched
          
    - name: Set up SSH
      run: |
        ssh-keygen -R "grit-web02.grit.ucsb.edu"
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 grit-web02.grit.ucsb.edu >> ~/.ssh/known_hosts
    - name: Unlock Dokku app (if locked)
      run: |
        ssh -o StrictHostKeyChecking=no dokku@grit-web02.grit.ucsb.edu dokku apps:unlock snippets || echo "App not locked or unlock failed, proceeding..."

    - name: Deploy to Dokku
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add dokku dokku@grit-web02.grit.ucsb.edu:snippets || git remote set-url dokku dokku@grit-web02.grit.ucsb.edu:snippets
        git push dokku +main
      working-directory: ./
#testing
